Repository justeat/fozzie, pull requests merged in 2022-08, with the labels that each got.

#388 v9.0.1 - Fix up throw error.
  CHANGELOG.md
  package.json
  src/scss/base/_grid.scss
  src/scss/tools/mixins/_type.scss
  src/test/scss/tools/mixins/type.spec.scss
Labels: Do not merge

#391 v9.1.0 - Adding spacing utility classes.
  CHANGELOG.md
  package.json
  src/scss/_dependencies.scss
  src/scss/tools/mixins/_index.scss
  src/scss/tools/mixins/_utilities.scss
  src/scss/trumps/_spacing.scss
  src/scss/trumps/_utilities.scss
Labels: enhancement

#394 v9.3.1 - update stylelint-config-fozzie version
  CHANGELOG.md
  package.json
  yarn.lock
Labels: dependencies
